services:
  app:
    build:
      context: ./docker
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: "${APP_ENV}"
      APP_DEBUG: "${APP_DEBUG}"
      DB_HOST: "${DB_HOST}"
    depends_on:
      - db
    networks:
      - app-network
    expose:
      - "9000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
